---
# Delete zookeeper.properties and write new zookeeper.properties file into the Config
- name: Delete existing Zookeeper properties
  file:
    path: "~/kafka/config/zookeeper.properties"
    state: absent

- name: Copy Zookeeper.properties into the given location
  copy: src=zookeeper.properties dest=~/kafka/config/
