---
# Fresh Download Zookeeper, Kafka, Scala in one bundle and build it

- name: Delete Kafka Directory if exists
  become: yes
  file:
    path: /home/{{host_username}}/kafka
    state: absent

- name: Download Kafka Zookeeper Bundle
  get_url:
    url: http://apache.mirror.digitalpacific.com.au/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz
    dest: /home/{{host_username}}/

- name: Unpack the bundle in home directory
  command: tar -xvzf /home/{{host_username}}/kafka_2.12-0.10.2.1.tgz

- name: Rename kafka_2.12-0.10.2.1 to kafka
  command: mv /home/{{host_username}}/kafka_2.12-0.10.2.1 /home/{{host_username}}/kafka

- name: Find Kafka Files ending in .tgz
  find:
    paths: /home/{{host_username}}
    patterns: "^kafka_.*.tgz"
    use_regex: true
  register: result

- name: Delete Kafka tar file
  file:
    path: "{{item.path}}"
    state: absent
  with_items: "{{result.files}}"
