---
- name: Apply Common Configuration to all the Nodes
  hosts: all
  remote_user: stephen

  roles:
    - common

- name: Zookeeper Integration and Configuration with all the server-group nodes
  hosts: server-group
  remote_user: stephen

  roles:
    - zookeeper
