---
# Reboot and Wait for server to come back up

- name: Reboot server
  become: yes
  command: /sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for server to come back
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 300
